name: Django CI

on: [push, pull_request]

env:
  DB_NAME: testdb
  DB_USER: root
  DB_HOST: 127.0.0.1
  DB_PORT: 3306

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y default-libmysqlclient-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo 'DB_NAME=${{ secrets.DB_NAME }}' > .env
        echo 'DB_USER=${{ secrets.DB_USER }}' >> .env
        echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env
        echo 'DB_HOST=${{ secrets.DB_HOST }}' >> .env
        echo 'DB_PORT=${{ secrets.DB_PORT }}'>> .env
        echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> .env

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test

