name: Django CI/CD Pipeline

on:
  push:
    branches: [ master ]
  
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: SGEDA
          MYSQL_USER: 'MABIALA'
          MYSQL_PASSWORD: 'Cherubinmab@2001'
          MYSQL_ROOT_PASSWORD: 'Cherubinmab@2001'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        DATABASE_URL: mysql://root:@127.0.0.1:3306/SGEDA
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        python manage.py test
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
        known_hosts: ${{ secrets.PYTHONANYWHERE_KNOWN_HOSTS }}
    
    - name: Deploy to PythonAnywhere
      run: |
        ssh ${{ secrets.PYTHONANYWHERE_USERNAME }}@ssh.pythonanywhere.com << EOF
          cd ~/SGEDA
          git pull origin main
          docker-compose down
          docker-compose up -d --build
        EOF
