name: Django CI with MySQL

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST || '127.0.0.1' }}  # Valeur par défaut
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install python-dotenv
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test